serenity.project.name = Demo Project using Serenity and JUnit
webdriver.driver = edge
headless.mode = true
edge.switches = --headless=new,--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--window-size=1920,1080,--remote-debugging-port=0,--disable-extensions,--no-first-run
serenity.test.root=com.ares.features